server:
    port: 80
spring:
    application:
        name: gateway-server
    cloud:
        gateway:
            # 默认开启网关
            enabled: true
            routes:
                -   # 路由id，保证唯一性
                    id: login-service-route
                    # 统一资源定位符
                    # 单击访问
                    # uri: http://localhost:8080
                    uri: lb://eureka-client-consumer
                    # 断言规则
                    predicates:
                        # 匹配路径的断言规则，如果匹配结果为false，则是404的页面
                        # 断言规则可以匹配多个，只要是有一个断言结果为false，那么整体则失败
                        - Path=/p/**
                        #- After=2022-12-10T10:36:51.259+08:00[Asia/Shanghai]
                        #- Before=2022-12-10T10:36:51.259+08:00[Asia/Shanghai]
                        #- Between=2022-12-10T10:36:51.259+08:00[Asia/Shanghai], 2022-12-10T11:36:51.259+08:00[Asia/Shanghai]
                        # 指定Cookie的断言规则
                        #- Cookie=aaa, bbb
                        # 指定请求头的断言规则
                        #- Header=aaa, bbb
                        # 指定请求参数的断言规则，注意请求参数必须为get方式的地址栏键值对传递
                        #- Query=aaa, bbb
                        # 指定请求方式的断言规则
                        - Method=GET, POST, PUT, DELETE
eureka:
    client:
        service-url:
            defaultZone: ${EUREKASERVER:http://localhost:8761/eureka/}
    instance: # eureka instance配置
        # 配置实例id
        instance-id: ${spring.application.name}:${server.port}
        # 显示ip
        prefer-ip-address: true
management:
    endpoints:
        web:
            exposure:
                # '*'暴露所有监控端点，默认只暴露health，info
                # 如果一个服务需要被监控，那么就需要将自身的一些信息暴露出去
                include: '*'
