server:
    port: 80
spring:
    application:
        name: gateway-server
    cloud:
        gateway:
            # 默认开启网关
            enabled: true
            routes:
                - # 路由id，保证唯一性
                    id: login-service-route
                    # 统一资源定位符
                    # 单击访问
                    # uri: http://localhost:8080
                    # 负载均衡访问
                    uri: lb://eureka-client-consumer
                    # 断言规则
                    predicates:
                        # 匹配路径的断言规则，如果匹配结果为false，则是404的页面
                        # 断言规则可以匹配多个，只要是有一个断言结果为false，那么整体则失败
                        - Path=/p/**
                        #- After=2022-12-10T10:36:51.259+08:00[Asia/Shanghai]
                        #- Before=2022-12-10T10:36:51.259+08:00[Asia/Shanghai]
                        #- Between=2022-12-10T10:36:51.259+08:00[Asia/Shanghai], 2022-12-10T11:36:51.259+08:00[Asia/Shanghai]
                        # 指定Cookie的断言规则
                        #- Cookie=aaa, bbb
                        # 指定请求头的断言规则
                        #- Header=aaa, bbb
                        # 指定请求参数的断言规则，注意请求参数必须为get方式的地址栏键值对传递
                        #- Query=aaa, bbb
                        # 指定请求方式的断言规则
                        - Method=GET, POST, PUT, DELETE
                    filters:
                        # 添加请求头的过滤器
                        #- AddRequestHeader=aaa, bbb
                        # 添加请求参数的过滤器
                        #- AddRequestParameter=aaa, bbb
                        # 添加响应头的过滤器，在浏览器中查看
                        #- AddResponseHeader=aaa, bbb
                        # 设置响应的状态码的过滤器
                        # - SetStatus=404
                        # 去除前缀路径数量的过滤器
                        # http://localhost:7001/abcd/01 -> http://localhost:7001/01
                        # http://localhost:7001/abcd/abcd/01 -> http://localhost:7001/abcd/01
                        # - StripPrefix=1
                        # 路径重写的过滤器，很好有效的保护了路径的安全
                        # - RewritePath=/p/?(?<segment>.*), /pro/$\{segment}
                        # 重定向的过滤器
                        # - RedirectTo=302, https://www.bilibili.com
                        # 配置请求限流器
                        - # 过滤器名称
                            name: RequestRateLimiter
                            # 过滤器参数
                            args:
                                # 通过spel表达式获取ioc容器中的bean
                                key-resolver: '#{@ipKeyResolver}'
                                # 生成令牌的速率
                                redis-rate-limiter.replenishRate: 1
                                # 令牌桶的容量
                                redis-rate-limiter.burstCapacity: 3
            discovery:
                locator:
                    # 开启动态路由，自动通过服务名称发现服务
                    enabled: true
                    # 服务名称转小写
                    lower-case-service-id: true
eureka:
    client:
        service-url:
            defaultZone: ${EUREKASERVER:http://localhost:8761/eureka/}
    instance: # eureka instance配置
        # 配置实例id
        instance-id: ${spring.application.name}:${server.port}
        # 显示ip
        prefer-ip-address: true
management:
    endpoints:
        web:
            exposure:
                # '*'暴露所有监控端点，默认只暴露health，info
                # 如果一个服务需要被监控，那么就需要将自身的一些信息暴露出去
                include: '*'
